// Generated by ego.
// DO NOT EDIT

//line installPage.ego:1

package views

import "fmt"
import "html"
import "io"
import "context"

import "github.com/codemicro/workboat/workboat/paths"

func InstallPage(ctx context.Context, w io.Writer) {

//line installPage.ego:8
	_, _ = io.WriteString(w, "\n    ")
//line installPage.ego:8
	{
		var EGO Page
		EGO.Title = "Login"
		EGO.UseHTMX = true
		EGO.Yield = func() {
//line installPage.ego:9
			_, _ = io.WriteString(w, "\n        <h1>Install into repository</h1>\n        <div hx-get=\"")
//line installPage.ego:10
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(paths.Make(paths.InstallSelectRepository))))
//line installPage.ego:10
			_, _ = io.WriteString(w, "\" hx-trigger=\"load\" hx-swap=\"outerHTML\">\n            Loading...\n        </div>\n    ")
		}
		EGO.Render(ctx, w)
	}
//line installPage.ego:14
	_, _ = io.WriteString(w, "\n")
//line installPage.ego:14
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
