// Code generated by Neon - DO NOT EDIT
// https://github.com/codemicro/go-neon

package views

import (
	"github.com/codemicro/workboat/workboat/paths"
	ntcHCTQYeuVOf "html"
	ntcEAndIxAtps "strings"
)

func LoginPage() string {
	ntcRijqFUuoGg := new(ntcEAndIxAtps.Builder)
	_, _ = ntcRijqFUuoGg.WriteString("\n    <a href=\"")
	_, _ = ntcRijqFUuoGg.WriteString(ntcHCTQYeuVOf.EscapeString(paths.Make(paths.AuthOauthOutbound)))
	_, _ = ntcRijqFUuoGg.WriteString("\">Click here to login via Gitea</a>\n")
	return ntcRijqFUuoGg.String()
}
