// Generated by ego.
// DO NOT EDIT

//line views/loginPage.ego:1

package views

import "fmt"
import "html"
import "io"
import "context"

import "github.com/codemicro/workboat/workboat/paths"

func LoginPage(ctx context.Context, w io.Writer) {

//line views/loginPage.ego:8
	_, _ = io.WriteString(w, "\n    <a href=\"")
//line views/loginPage.ego:8
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(paths.Make(paths.AuthOauthOutbound))))
//line views/loginPage.ego:8
	_, _ = io.WriteString(w, "\">Click here to login via Gitea</a>\n")
//line views/loginPage.ego:9
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
