// Generated by ego.
// DO NOT EDIT

//line page.ego:1

package views

import "fmt"
import "html"
import "io"
import "context"

type Page struct {
	Title   string
	UseHTMX bool
	Head    func()
	Yield   func()
}

func (p *Page) Render(ctx context.Context, w io.Writer) {

//line page.ego:13
	_, _ = io.WriteString(w, "\n\n<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n    <title>")
//line page.ego:19
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(p.Title)))
//line page.ego:19
	if p.Title != "" {
//line page.ego:19
		_, _ = io.WriteString(w, " | ")
//line page.ego:19
	}
//line page.ego:19
	_, _ = io.WriteString(w, "Workboat</title>\n    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\n    ")
//line page.ego:21
	if p.Head != nil {
		p.Head()
	}
//line page.ego:24
	_, _ = io.WriteString(w, "\n</head>\n<body>\n    <nav class=\"navbar navbar-dark bg-dark\">\n        <div class=\"container-fluid\">\n            <span class=\"navbar-brand mb-0 h1\">Workboat</span>\n        </div>\n    </nav>\n\n    ")
//line page.ego:32
	if p.Yield != nil {
//line page.ego:33
		_, _ = io.WriteString(w, "\n        <div class=\"container mt-3\">\n            ")
//line page.ego:34
		p.Yield()
//line page.ego:35
		_, _ = io.WriteString(w, "\n        </div>\n    ")
//line page.ego:36
	}
//line page.ego:37
	_, _ = io.WriteString(w, "\n\n    ")
//line page.ego:38
	if p.UseHTMX {
//line page.ego:39
		_, _ = io.WriteString(w, "\n        <script src=\"https://unpkg.com/htmx.org@1.8.3\"></script>\n    ")
//line page.ego:40
	}
//line page.ego:41
	_, _ = io.WriteString(w, "\n    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>\n</body>\n</html>\n")
//line page.ego:44
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
